---
name: "Spotless Check"
"on":
  push:
    branches:
    - "main"
  pull_request: null
jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "corretto"
        java-version: "21"
    - uses: "gradle/actions/setup-gradle@v3"
    - name: "Run Spotless Check"
      run: "./gradlew spotlessCheck"
